# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76066433515b87bac8fcb4347f1bccade07192bc1c1625dd0a22af738837a91168df826850bcc7cef6f53193669599070a696d5ffc31c447fb70ea3a41c1ff80

test:
  secret_key_base: 7933ce711cf8852c91e5f8c16c8350d80ad90374b89209ce4ca2742f984c66b0b0c0a500785fe400df45cf73ad4f0bcc60d78b0a485d9211e4dc81928c42ebae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
